//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string body { get; set; }
        public Nullable<bool> active { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    
        public virtual task task { get; set; }
        public virtual task task1 { get; set; }
        public virtual user user { get; set; }
    }
}
