//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string path { get; set; }
        public Nullable<int> submit_by { get; set; }
        public Nullable<int> assignment_id { get; set; }
    
        public virtual group group { get; set; }
    }
}
