//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMSdbEntities : DbContext
    {
        public TMSdbEntities()
            : base("name=TMSdbEntities")
        {
        }

        public static TMSdbEntities Create()
        {
            return new TMSdbEntities();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_course> student_course { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<submission> submissions { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<topic> topics { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
